server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registration_db?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# less secure apps and app passwords don't work and will get disabled on 30th september 2024
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: wavebank782@gmail.com
#    password: o3H2svdL9YJPCAo
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
